[colors.primary]
background = '#171714'
foreground = '#f8f8f2'

[colors.normal]
black = '#272822'
red = '#f92672'
green = '#a6e22e'
yellow = '#f4bf75'
blue = '#66d9ef'
magenta = '#ae81ff'
cyan = '#a1efe4'
white = '#f8f8f2'

[colors.bright]
black = '#75715e'
red = '#f92672'
green = '#a6e22e'
yellow = '#f4bf75'
blue = '#66d9ef'
magenta = '#ae81ff'
cyan = '#a1efe4'
white = '#f9f8f5'

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Beam", blinking = "Never" }

[font]
size = 12

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 12
y = 12
